### ISSUE TITLE
Graph iterators

### ISSUE THREAD

**Issue by athityakumar** [SciRuby/networkx.rb#2]
### Description

```ruby
# Assuming that Graph building is complete,
graph.each do |node, node_neighbors|
  # do whatever is required
end
```

- Relevant Issues : (optional)
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [x] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by universato** [comment]
`String` has `each_char`, `each_line` e.t.c., but It doesn't have simple `each`.
`Graph` has `each_node`, `each_edge` e.t.c., so I think it shouldn't have simple `each`.
It's because he behavior of simple `each` is not obvious.
