### ISSUE TITLE
Upgrade the versions of Ruby and Bundler

### ISSUE THREAD

**Issue by universato** [SciRuby/networkx.rb#24]
### Description

Can you please upgrade the versions of Ruby and Bundler?

Ruby and Bundler is old, so CI doesn't work.

https://travis-ci.org/github/SciRuby/networkx.rb/jobs/769100515
[![Image from Gyazo](https://i.gyazo.com/4ae47460c0decebbba06d32d12082db3.png)](https://gyazo.com/4ae47460c0decebbba06d32d12082db3)

https://travis-ci.org/github/SciRuby/networkx.rb/jobs/769100517
[![Image from Gyazo](https://i.gyazo.com/d71e3bb417f9467eeb67d66d5c708426.png)](https://gyazo.com/d71e3bb417f9467eeb67d66d5c708426)

`.travis.yml`
```yaml
rvm:
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'
```

These Ruby versions are EOL and not  officially supported.

<hr>

- Relevant Issues : (optional)
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [ ] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [x] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by Ashvith** [comment]
Hey @universato, [this alternative fork](https://github.com/sciruby-jp/networkx.rb) has seen some commit, although I cannot see any issues tab to communicate with the contributors.

**Comment by universato** [comment]
The commit https://github.com/SciRuby/networkx.rb/commit/c2c3f994bfece841f23acd96e0fe559af3a444c8  redolved this issue.
