### ISSUE TITLE
I recommend @universato as the owner.

### ISSUE THREAD

**Issue by kojix2** [SciRuby/networkx.rb#26]
Hi NetworkX.rb developers @npochhi, @athityakumar

cc: @pjotrp, @v0dro 

I am @kojix2, a member of the SciRuby and IRuby projects.

I would like to put it simply.
I recommend @universato as the one of the owners of the project. He has made many improvements to the NetworkX.rb project. Some improvements were sent as pull requests. Unfortunately, the pull request was not reviewed and was recently closed. (#21) (#23) (#25) So I created a fork on [sciruby-jp](https://github.com/sciruby-jp) and added commit rights to universato. ((sciruby-jp) is not a real organization as it has been inactive for quite some time. I had the right to create a repository in that namespace, so I simply used it.)

repo: https://github.com/sciruby-jp/networkx.rb

I did not want to do this. Because if @universato had commit rights to the SciRuby/networkx.rb repository from the beginning, this work would not have been necessary at all.

There are many OSS projects in the world. However, most of them do not get new committers. Only a few worthy projects have acquired new maintainers and committers to keep them alive. Otherwise, our libraries would disappear without being used. Therefore, it is very valuable for a project to get new committers. This way, the library becomes truly useful and the founder is honored.

Currently, sciruby-jp/NetworkX.rb is 157 commits ahead.

Please consider my proposal.

Best regards

**Comment by athityakumar** [comment]
Hey @kojix2 👋 

Thanks for proposing this - and I completely agree with adding new owners/committers to the code repos so that the projects keep getting developed actively (and get an active community too).

Looks like I don't have access to provide admin/write access to anyone in this repo - but I'd be completely aligned for one of the GH repo/org admins to provide write/admin access to @universato! Thanks for this suggestion 😄

**Comment by pjotrp** [comment]
Let's discuss on matrix. Please join

https://matrix.to/#/#sciruby:matrix.org

**Comment by kojix2** [comment]
Thank you @athityakumar for your reply and confirmation of access rights!

> Looks like I don't have access to provide admin/write access to anyone in this repo

That sounds serious. If you do not have the administrative authority, then who currently has the authority? Does @npochhi have administrative privileges?  Maybe none of the currently active members can make the change...

Thank you @pjotrp

I joined sciruby:matrix.org on 2022-03-18.
However, I think there is a general consensus among the currently active members. The problem is that we don't know who has admin rights and may not be able to contact them.

**Comment by pjotrp** [comment]
I added @universato and gave @athityakumar admin rights to the repo

**Comment by kojix2** [comment]
With your help, this problem seems to be finally solved. 
@universato, please try to see if the commit right works properly. 
Many thanks to you all.

**Comment by universato** [comment]
@athityakumar 

Hi, I'm universato.

I became a member of SciRuby.
However, I do not seem to have the right to commit and merge PR on this repository.

I have a will to maintain this repository now, which is great asset.
pjotrp-san gave you admin rights, so could you give me the rights too?

And, pjotrp-san wants to talk with you in [matrix](https://matrix.to/#/#sciruby:matrix.org).
Can you please join [matrix](https://matrix.to/#/#sciruby:matrix.org).

**Comment by athityakumar** [comment]
@universato - Provided you w/ the required access! 👍

**Comment by universato** [comment]
@athityakumar

Thank you very much. 
I can commit 🎉 

I have one more request.
I and kojix2 want to update gem `networkx`.
Could you please add me(universato) as owner of the gem?
https://rubygems.org/gems/networkx
https://rubygems.org/gems/networkx/owners

**Comment by kojix2** [comment]
[sciruby-jp/networkx.rb](https://github.com/sciruby-jp/networkx.rb) has been archived .
