### ISSUE TITLE
Graph accessors

### ISSUE THREAD

**Issue by athityakumar** [SciRuby/networkx.rb#3]
### Description

```ruby
# Assuming that Graph building is complete,
graph.nodes
#=> List of nodes

graph.edges
#=> List of edges

graph.nodes_count
#=> Number of nodes

graph.edges_count
#=> Number of edges
```

- Relevant Issues : (optional)
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [ ] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by universato** [comment]
Done!

Note:
`nodes_count` -> `number_of_nodes`
`edges_count` -> `number_of_edges`
