### ISSUE TITLE
Induced subgraphs

### ISSUE THREAD

**Issue by athityakumar** [SciRuby/networkx.rb#4]
### Description

```ruby
# Assuming that Graph building is complete,

graph[node_1, node_2, node_3, hop_size: 2]
#=> Subgraph involving neighbors that are close to given set of nodes, within given hop_size
```

- Relevant Issues : (optional)
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [ ] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by universato** [comment]
No one seems to want to implement it
