### ISSUE TITLE
[Long Term] Support for Import / Export modules

### ISSUE THREAD

**Issue by athityakumar** [SciRuby/networkx.rb#5]
### Description

Having the pleasure and opportunity of authoring [daru-io](https://github.com/SciRuby/daru-io) plugin-gem that extends Import / Export modules to the [daru](https://github.com/SciRuby/daru) gem, I understand the amount of work that is required for adding similar IO modules to networkx. This could be a summer of work by it's own - but it can also be interfaced with daru-io as a shortcut.

If the trade-off of including daru as a runtime dependency of networkx.rb is fine (installation-wise), then bridging networkx with daru-io seems a better alternative than adding custom IO modules.

- Relevant Issues : (optional)
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [x] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by universato** [comment]
Sadly the development of daru, daru-io seems to have been stopped
