### ISSUE TITLE
[Long Term] Support for visualization

### ISSUE THREAD

**Issue by athityakumar** [SciRuby/networkx.rb#6]
### Description

This task of adding visualizations to the networkx library is also closely related to daru and daru-view gems. As noted in #5, the view modules of networkx.rb could be bridged through daru-view rather than custom views. However, this bridging again takes a lot effort and needs to be supported by v0.2.0.

- Relevant Issues : #5 
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [x] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by universato** [comment]
I have interest about visualization, but it seems very difficult. 
It takes a lot of time to introduce it.
