### ISSUE TITLE
Extending basic graph formation

### ISSUE THREAD

**Issue by ajeetdsouza** [SciRuby/networkx.rb#9]
### Description

`add_nodes` should be renamed to `add_nodes_from` and `add_edges` should be made `add_edges_from` to provide familiarity to NetworkX users migrating from Python. Additionally, support for `remove_node`, `remove_nodes_from`, `remove_edge` and `remove_edges_from` should be provided.

However, the graph format must be finalised first (please see the issue referenced).

- Relevant Issues : https://github.com/athityakumar/networkx.rb/issues/8
- Relevant PRs : (optional)
- Type of issue :
  - User mode :
    - [ ] Installation
    - [x] Feature request
    - [ ] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by ajeetdsouza** [comment]
I'd like to work on this issue, once the basic graph format has been decided.

**Comment by universato** [comment]
Done!
I added alias (`remove_nodes_from` and `remove_edges_from`)
Graph has also `add_nodes_from` and `add_edges_from`.
